a=int(input("Enter the 1st number"))
b=int(input("Enter the 2nd number"))
addition= a+b
subtraction= a-b
multiplication= a*b
division=a/b
intdivision=a//b
remainder=a%b
print(addition,subtraction,multiplication,division,intdivision,remainder,sep="\n")
